interface ProcessEnv {
  NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID?: string;
  NEXT_PUBLIC_DEFAULT_PROVIDER?: string;
  NEXT_PUBLIC_OPENROUTER_API_KEY?: string;
  NEXT_PUBLIC_OPENROUTER_BASE_URL?: string;
  NEXT_PUBLIC_OPENROUTER_MODEL?: string;
  NEXT_PUBLIC_SEED_OPENROUTER_KEY?: string;
  NEXT_PUBLIC_OPENAI_API_KEY?: string;
  NEXT_PUBLIC_OPENAI_BASE_URL?: string;
  NEXT_PUBLIC_OPENAI_MODEL?: string;
  NEXT_PUBLIC_SEED_OPENAI_KEY?: string;
  NEXT_PUBLIC_ANTHROPIC_API_KEY?: string;
  NEXT_PUBLIC_CLAUDE_API_KEY?: string;
  NEXT_PUBLIC_CLAUDE_BASE_URL?: string;
  NEXT_PUBLIC_CLAUDE_MODEL?: string;
  NEXT_PUBLIC_GEMINI_API_KEY?: string;
  NEXT_PUBLIC_GOOGLE_API_KEY?: string;
  NEXT_PUBLIC_GEMINI_BASE_URL?: string;
  NEXT_PUBLIC_GEMINI_MODEL?: string;
  NEXT_PUBLIC_DEEPSEEK_API_KEY?: string;
  NEXT_PUBLIC_DEEPSEEK_BASE_URL?: string;
  NEXT_PUBLIC_DEEPSEEK_MODEL?: string;
  NEXT_PUBLIC_ZAI_API_KEY?: string;
  NEXT_PUBLIC_SEED_ZAI_KEY?: string;
  NEXT_PUBLIC_ZAI_BASE_URL?: string;
  NEXT_PUBLIC_ZAI_MODEL?: string;
  NEXT_PUBLIC_MINIMAX_API_KEY?: string;
  NEXT_PUBLIC_MINIMAX_BASE_URL?: string;
  NEXT_PUBLIC_MINIMAX_MODEL?: string;
  NEXT_PUBLIC_NEMOTRON_API_KEY?: string;
  NEXT_PUBLIC_NEMOTRON_BASE_URL?: string;
  NEXT_PUBLIC_NEMOTRON_MODEL?: string;
  NEXT_PUBLIC_OLLAMA_ENABLED?: string;
  NEXT_PUBLIC_OLLAMA_BASE_URL?: string;
  NEXT_PUBLIC_OLLAMA_MODEL?: string;
}

declare global {
  namespace NodeJS {
    interface ProcessEnv extends ProcessEnv {}
  }
}

export {};
